// AUTO-GENERATED by scripts/embed-migrations.mjs — do not edit.
// Regenerate with: npm run db:generate
export interface Migration {
  idx: number;
  tag: string;
  statements: string[];
}

export const migrations: Migration[] = [
  {
    idx: 0,
    tag: "0000_worried_thunderbolt_ross",
    statements: [
      'CREATE TABLE `comments` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`issue_id` integer NOT NULL,\n\t`body` text NOT NULL,\n\t`author_type` text NOT NULL,\n\t`author_token_id` integer,\n\t`author_name` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`issue_id`) REFERENCES `issues`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT "comments_author_type" CHECK("comments"."author_type" IN (\'agent\',\'human\'))\n);',
      "CREATE INDEX `comments_issue` ON `comments` (`issue_id`);",
      "CREATE TABLE `issue_labels` (\n\t`issue_id` integer NOT NULL,\n\t`label_id` integer NOT NULL,\n\tPRIMARY KEY(`issue_id`, `label_id`),\n\tFOREIGN KEY (`issue_id`) REFERENCES `issues`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`label_id`) REFERENCES `labels`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE TABLE `issue_links` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`source_id` integer NOT NULL,\n\t`target_id` integer NOT NULL,\n\t`type` text NOT NULL,\n\t`created_by_token_id` integer,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`source_id`) REFERENCES `issues`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`target_id`) REFERENCES `issues`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"issue_links_type\" CHECK(\"issue_links\".\"type\" IN ('blocks','depends_on','relates_to','duplicates'))\n);",
      "CREATE INDEX `issue_links_source` ON `issue_links` (`source_id`);",
      "CREATE INDEX `issue_links_target` ON `issue_links` (`target_id`);",
      "CREATE UNIQUE INDEX `issue_links_unique` ON `issue_links` (`source_id`,`target_id`,`type`);",
      'CREATE TABLE `issues` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`project_id` integer NOT NULL,\n\t`number` integer NOT NULL,\n\t`key` text NOT NULL,\n\t`kind` text DEFAULT \'issue\' NOT NULL,\n\t`epic_id` integer,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`status` text DEFAULT \'open\' NOT NULL,\n\t`priority` integer DEFAULT 2 NOT NULL,\n\t`assignee_type` text,\n\t`assignee` text,\n\t`created_by_token_id` integer,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\t`closed_at` integer,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT "issues_kind" CHECK("issues"."kind" IN (\'epic\',\'issue\')),\n\tCONSTRAINT "issues_priority" CHECK("issues"."priority" BETWEEN 0 AND 4),\n\tCONSTRAINT "issues_assignee_type" CHECK("issues"."assignee_type" IS NULL OR "issues"."assignee_type" IN (\'agent\',\'human\'))\n);',
      "CREATE UNIQUE INDEX `issues_key_unique` ON `issues` (`key`);",
      "CREATE INDEX `issues_project_status` ON `issues` (`project_id`,`status`);",
      "CREATE INDEX `issues_epic` ON `issues` (`epic_id`);",
      "CREATE INDEX `issues_status` ON `issues` (`status`);",
      "CREATE UNIQUE INDEX `issues_project_number` ON `issues` (`project_id`,`number`);",
      "CREATE TABLE `labels` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`project_id` integer NOT NULL,\n\t`name` text NOT NULL,\n\t`color` text,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `labels_project_name` ON `labels` (`project_id`,`name`);",
      "CREATE TABLE `projects` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`key` text NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text,\n\t`next_issue_number` integer DEFAULT 1 NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);",
      "CREATE UNIQUE INDEX `projects_key_unique` ON `projects` (`key`);",
      "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`expires_at` integer NOT NULL\n);",
      "CREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);",
      "CREATE TABLE `statuses` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`project_id` integer,\n\t`name` text NOT NULL,\n\t`category` text NOT NULL,\n\t`sort_order` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"statuses_category\" CHECK(\"statuses\".\"category\" IN ('todo','active','done'))\n);",
      "CREATE UNIQUE INDEX `statuses_project_name` ON `statuses` (`project_id`,`name`);",
      "CREATE TABLE `tokens` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`last_used_at` integer,\n\t`revoked_at` integer\n);",
      "CREATE UNIQUE INDEX `tokens_name_unique` ON `tokens` (`name`);",
      "CREATE UNIQUE INDEX `tokens_token_hash_unique` ON `tokens` (`token_hash`);",
    ],
  },
];
