// Compiles src/web/app.css with the Tailwind 4 CLI and emits src/web/app.css.gen.ts
// so the stylesheet ships inside the JS bundle — no file to resolve at runtime under
// npx/bunx (same reasoning as embed-migrations.mjs). Run via `npm run css:generate`;
// the generated file is committed, so tests and fresh checkouts never need Tailwind.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tmp = mkdtempSync(join(tmpdir(), "agenticket-css-"));
const outFile = join(tmp, "app.css");

try {
  execFileSync(
    process.execPath,
    [
      join(root, "node_modules/@tailwindcss/cli/dist/index.mjs"),
      "-i",
      join(root, "src/web/app.css"),
      "-o",
      outFile,
      "--minify",
    ],
    { stdio: ["ignore", "inherit", "inherit"] },
  );
  const css = readFileSync(outFile, "utf8").trim();
  const out = `// AUTO-GENERATED by scripts/embed-css.mjs — do not edit.
// Regenerate with: npm run css:generate
export const APP_CSS = ${JSON.stringify(css)};
`;
  writeFileSync(join(root, "src/web/app.css.gen.ts"), out);
  console.log(`embedded ${(css.length / 1024).toFixed(1)} kB of compiled CSS into src/web/app.css.gen.ts`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
